# vim:set ft=tmux:
%hidden MODULE_NAME="priv_ip"

set -gq "@catppuccin_${MODULE_NAME}_icon" "󰱓 "
set -gqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(/bin/sh #{E:HOME}/.config/tmux/catppuccin-custom/priv_ip.sh)"

source -F "#{E:HOME}/.tmux/plugins/tmux/utils/status_module.conf"
