POOL=zroot
CAPACITY_WARN=70
CAPACITY_CRITICAL=80
PRUNE_EXPIRED=yes
SNAPSHOT_PREFIX=autosnap_v2
PREPACMAN_PREFIX=pre_update_v2
PREPACMAN_KEEP=3
PREPACMAN_DATASET=zroot/ROOT/arch
declare -A SNAPSHOT_POLICY_DATASETS=(
  ["default"]="zroot/ROOT/arch:n zroot/home:n zroot/local/development:n"
)
declare -A SNAPSHOT_POLICY_KEEP=(
  ["default|10min"]=4
  ["default|hourly"]=4
  ["default|daily"]=3
  ["default|weekly"]=2
  ["default|monthly"]=2
)
