-- Generated from ENVariables.conf. Edit the matching Lua file going forward.
local H = require("lua.hypr_helpers")
hl.env(H.expand("GDK_BACKEND"), H.expand("wayland,x11,*"))
hl.env(H.expand("QT_QPA_PLATFORM"), H.expand("wayland;xcb"))
hl.env(H.expand("CLUTTER_BACKEND"), H.expand("wayland"))
hl.env(H.expand("XDG_CURRENT_DESKTOP"), H.expand("Hyprland"))
hl.env(H.expand("XDG_SESSION_DESKTOP"), H.expand("Hyprland"))
hl.env(H.expand("XDG_SESSION_TYPE"), H.expand("wayland"))
hl.env(H.expand("QT_AUTO_SCREEN_SCALE_FACTOR"), H.expand("1"))
hl.env(H.expand("QT_WAYLAND_DISABLE_WINDOWDECORATION"), H.expand("1"))
hl.env(H.expand("QT_QPA_PLATFORMTHEME"), H.expand("qt5ct"))
hl.env(H.expand("QT_QPA_PLATFORMTHEME"), H.expand("qt6ct"))
hl.env(H.expand("QT_QUICK_CONTROLS_STYLE"), H.expand("org.hyprland.style"))
hl.env(H.expand("GDK_SCALE"), H.expand("1"))
hl.env(H.expand("QT_SCALE_FACTOR"), H.expand("1"))
hl.env(H.expand("HYPRCURSOR_THEME"), H.expand("Bibata-Modern-Ice"))
hl.env(H.expand("HYPRCURSOR_SIZE"), H.expand("24"))
hl.env(H.expand("MOZ_ENABLE_WAYLAND"), H.expand("1"))
hl.env(H.expand("ELECTRON_OZONE_PLATFORM_HINT"), H.expand("auto"))
