-- Generated from Laptops.conf. Edit the matching Lua file going forward.
local H = require("lua.hypr_helpers")
H.set("mainMod", H.expand("SUPER"))
H.set("scriptsDir", H.expand("$HOME/.config/hypr/scripts"))
H.set("UserConfigs", H.expand("$HOME/.config/hypr/UserConfigs"))
H.set("Touchpad_Device", H.expand("asue1209:00-04f3:319f-touchpad"))
H.bind(H.expand("xf86KbdBrightnessDown"), "exec", H.expand("$scriptsDir/BrightnessKbd.sh --dec"), { repeating = true })
H.bind(H.expand("xf86KbdBrightnessUp"), "exec", H.expand("$scriptsDir/BrightnessKbd.sh --inc"), { repeating = true })
H.bind(H.expand("xf86Launch1"), "exec", H.expand("rog-control-center"))
H.bind(H.expand("xf86Launch3"), "exec", H.expand("asusctl led-mode -n"))
H.bind(H.expand("xf86Launch4"), "exec", H.expand("asusctl profile -n"))
H.bind(H.expand("xf86MonBrightnessDown"), "exec", H.expand("$scriptsDir/Brightness.sh --dec"), { repeating = true })
H.bind(H.expand("xf86MonBrightnessUp"), "exec", H.expand("$scriptsDir/Brightness.sh --inc"), { repeating = true })
H.bind(H.expand("xf86TouchpadToggle"), "exec", H.expand("$scriptsDir/TouchPad.sh"))
H.bind(H.expand("SUPER + F6"), "exec", H.expand("$scriptsDir/ScreenShot.sh --now"))
H.bind(H.expand("SUPER + SHIFT + F6"), "exec", H.expand("$scriptsDir/ScreenShot.sh --area"))
H.bind(H.expand("SUPER + CTRL + F6"), "exec", H.expand("$scriptsDir/ScreenShot.sh --in5"))
H.bind(H.expand("SUPER + ALT + F6"), "exec", H.expand("$scriptsDir/ScreenShot.sh --in10"))
H.bind(H.expand("ALT + F6"), "exec", H.expand("$scriptsDir/ScreenShot.sh --active"))
H.set("TOUCHPAD_ENABLED", H.expand("true"))
hl.device({ name = H.var("Touchpad_Device"), enabled = (H.var("TOUCHPAD_ENABLED") == "true") })
