-- Generated from Startup_Apps.conf. Edit the matching Lua file going forward.
local H = require("lua.hypr_helpers")
H.set("scriptsDir", H.expand("$HOME/.config/hypr/scripts"))
H.set("UserScripts", H.expand("$HOME/.config/hypr/UserScripts"))
H.set("wallDIR", H.expand("$HOME/Pictures/wallpapers"))
H.set("lock", H.expand("$scriptsDir/LockScreen.sh"))
H.set("SwwwRandom", H.expand("$UserScripts/WallpaperAutoChange.sh"))
H.set("livewallpaper", H.expand("\"\""))
H.exec_once(H.expand("$UserScripts/RainbowBorders.sh"))
H.exec_once(H.expand("$UserScripts/ApplyUserPreferences.sh"))
H.exec_once(H.expand("sh -c 'sleep 2; pkill -x hypridle; setsid hypridle -c \"$HOME/.config/hypr/UserConfigs/hypridle.conf\" >/tmp/hypridle-user.log 2>&1 &'"))
H.exec_once(H.expand("[workspace 1 silent] kitty --detach -e tmux new"))
H.exec_once(H.expand("[workspace 2 silent] vivaldi"))
H.exec_once(H.expand("[workspace 10 silent] ferdium"))
H.exec_once(H.expand("gnome-keyring-daemon --start --components=secrets"))
