-- Generated from UserKeybinds.conf. Edit the matching Lua file going forward.
local H = require("lua.hypr_helpers")
H.set("mainMod", H.expand("SUPER"))
H.set("scriptsDir", H.expand("$HOME/.config/hypr/scripts"))
H.set("UserScripts", H.expand("$HOME/.config/hypr/UserScripts"))
H.set("UserConfigs", H.expand("$HOME/.config/hypr/UserConfigs"))
H.bind(H.expand("SUPER + D"), "exec", H.expand("pkill rofi || true && rofi -show drun -modi drun, filebrowser, run, window"))
H.bind(H.expand("SUPER + B"), "exec", H.expand("xdg-open \"https://\""))
H.bind(H.expand("SUPER + E"), "exec", H.expand("$files"))
hl.unbind(H.expand("SUPER + H"))
hl.unbind(H.expand("SUPER + SHIFT + H"))
H.bind(H.expand("SUPER + H"), "movefocus", H.expand("l"))
H.bind(H.expand("SUPER + J"), "movefocus", H.expand("d"))
H.bind(H.expand("SUPER + K"), "movefocus", H.expand("u"))
H.bind(H.expand("SUPER + L"), "movefocus", H.expand("r"))
H.bind(H.expand("SUPER + SHIFT + H"), "exec", H.expand("$scriptsDir/KeyHints.sh"))
H.bind(H.expand("SUPER + ALT + R"), "exec", H.expand("$scriptsDir/Refresh.sh"))
H.bind(H.expand("SUPER + ALT + E"), "exec", H.expand("$scriptsDir/RofiEmoji.sh"))
H.bind(H.expand("SUPER + S"), "exec", H.expand("$scriptsDir/RofiSearch.sh"))
H.bind(H.expand("SUPER + ALT + O"), "exec", H.expand("$scriptsDir/ChangeBlur.sh"))
H.bind(H.expand("SUPER + SHIFT + G"), "exec", H.expand("$scriptsDir/GameMode.sh"))
H.bind(H.expand("SUPER + ALT + L"), "exec", H.expand("$scriptsDir/ChangeLayout.sh"))
H.bind(H.expand("SUPER + SHIFT + L"), "exec", H.expand("$scriptsDir/LockScreen.sh"))
H.bind(H.expand("SUPER + ALT + V"), "exec", H.expand("$scriptsDir/ClipManager.sh"))
H.bind(H.expand("SUPER + CTRL + R"), "exec", H.expand("$scriptsDir/RofiThemeSelector.sh"))
H.bind(H.expand("SUPER + CTRL + SHIFT + R"), "exec", H.expand("pkill rofi || true && $scriptsDir/RofiThemeSelector-modified.sh"))
hl.unbind(H.expand("SUPER + N"))
H.bind(H.expand("SUPER + N"), "exec", H.expand("swaync-client -t -sw"))
hl.unbind(H.expand("SUPER + SHIFT + F"))
hl.unbind(H.expand("SUPER + CTRL + F"))
hl.unbind(H.expand("SUPER + F"))
H.bind(H.expand("SUPER + SHIFT + F"), "fullscreen", H.expand("0"))
H.bind(H.expand("SUPER + CTRL + F"), "fullscreen", H.expand("1"))
H.bind(H.expand("SUPER + F"), "fullscreen", H.expand("1"))
H.bind(H.expand("SUPER + SPACE"), "togglefloating", H.expand(""))
H.bind(H.expand("SUPER + ALT + SPACE"), "exec", H.expand("hyprctl dispatch workspaceopt allfloat"))
H.bind(H.expand("SUPER + SHIFT + Return"), "exec", H.expand("$scriptsDir/Dropterminal.sh $term"))
H.bind(H.expand("SUPER + ALT + mouse_down"), "exec", H.expand("hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')\""))
H.bind(H.expand("SUPER + ALT + mouse_up"), "exec", H.expand("hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')\""))
H.bind(H.expand("SUPER + CTRL + ALT + B"), "exec", H.expand("pkill -SIGUSR1 waybar"))
H.bind(H.expand("SUPER + CTRL + B"), "exec", H.expand("$scriptsDir/WaybarStyles.sh"))
H.bind(H.expand("SUPER + ALT + B"), "exec", H.expand("$scriptsDir/WaybarLayout.sh"))
H.bind(H.expand("SUPER + SHIFT + M"), "exec", H.expand("$UserScripts/RofiBeats.sh"))
H.bind(H.expand("SUPER + W"), "exec", H.expand("$UserScripts/WallpaperSelect.sh"))
H.bind(H.expand("SUPER + SHIFT + W"), "exec", H.expand("$UserScripts/WallpaperEffects.sh"))
H.bind(H.expand("CTRL + ALT + W"), "exec", H.expand("$UserScripts/WallpaperRandom.sh"))
H.bind(H.expand("SUPER + CTRL + O"), "exec", H.expand("hyprctl setprop active opaque toggle"))
H.bind(H.expand("SUPER + SHIFT + K"), "exec", H.expand("$scriptsDir/KeyBinds.sh"))
H.bind(H.expand("SUPER + SHIFT + A"), "exec", H.expand("$scriptsDir/Animations.sh"))
H.bind(H.expand("SUPER + SHIFT + O"), "exec", H.expand("$UserScripts/ZshChangeTheme.sh"))
H.bind(H.expand("ALT_L + SHIFT_L"), "exec", H.expand("$scriptsDir/SwitchKeyboardLayout.sh"), { locked = true, non_consuming = true })
H.bind(H.expand("SHIFT_L + ALT_L"), "exec", H.expand("$scriptsDir/Tak0-Per-Window-Switch.sh"), { locked = true, non_consuming = true })
H.bind(H.expand("SUPER + ALT + C"), "exec", H.expand("$UserScripts/RofiCalc.sh"))
hl.unbind(H.expand("SUPER + SHIFT + S"))
H.bind(H.expand("SUPER + SHIFT + S"), "exec", H.expand("$UserScripts/ScreenShot.sh --swappy"))
